project:
  type: website
  output-dir: docs

website:
  title: "Daniel Malinsky"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
  page-footer:
    background: light # or `dark`
    left: Copyright 2024, Daniel Malinsky
  
format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: full

editor: visual

