project:
  type: website
  output-dir: docs

website:
  title: "Daniel Malinsky"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: full

editor: visual

